export const NET_ENV = localStorage.getItem("NET_ENV") || "testnet";
export const initialBase64 = "oRzrCwYAAAAKAQAMAgweAyonBFEIBVlXB7ABzAEI/AJgBtwDoAEK/AQFDIEFLAAQAQsCBgIRAhICEwACAgABAQcBAAACAAwBAAECAwwBAAEEBAIABQUHAAAJAAEAAQ8FBgEAAgcICQECAwwFAQEMAw0OAQEMBA4LDAAFCgMEAAEEAgcDCgQNAggABwgEAAILAgEIAAsDAQgAAQoCAQgFAQkAAQsBAQkAAQgABwkAAgoCCgIKAgsBAQgFBwgEAgsDAQkACwIBCQABCwIBCAABBggEAQUBCwMBCAACCQAFDENvaW5NZXRhZGF0YQZPcHRpb24IVEVNUExBVEULVHJlYXN1cnlDYXAJVHhDb250ZXh0A1VybARjb2luD2NyZWF0ZV9jdXJyZW5jeQtkdW1teV9maWVsZARpbml0FW5ld191bnNhZmVfZnJvbV9ieXRlcwZvcHRpb24UcHVibGljX2ZyZWV6ZV9vYmplY3QPcHVibGljX3RyYW5zZmVyBnNlbmRlcgRzb21lCHRlbXBsYXRlCHRyYW5zZmVyCnR4X2NvbnRleHQDdXJsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAwgAQHoQ81oAAAIBBgoCGRhXcmFwcGVyIFRva2VuaXplZCBTeW1ib2wKAhcWV3JhcHBlciBUb2tlbml6ZWQgTmFtZQoCHh1XcmFwcGVyIFRva2VuaXplZCBEZXNjcmlwdGlvbgoCOThodHRwczovL3RoLmJpbmcuY29tL3RoL2lkL09JUC5LSWJRVlc5OTVzZG9tUDdoQXVzaFFnSGFIYQACAQgBAAAAAAIUCwAHAQcCBwMHBAcFEQY4AAoBOAEMAgwDCwI4AgsDCwEuEQU4AwIA";
export const constants_alias = [
    { name: "constant_0", alias: "TOTAL_SUPPLY" },
    { name: "constant_1", alias: "DECIMALS" },
    { name: "constant_2", alias: "SYMBOL" },
    { name: "constant_3", alias: "NAME" },
    { name: "constant_4", alias: "DESCRIPTION" },
    { name: "constant_5", alias: "ICON_URL" },
]; 